name: KeepMyChunks
version: '${project.version}'
main: com.lyttldev.keepmychunks.KeepMyChunks
api-version: '1.20'
commands:
    keepmychunks:
        usage: /keepmychunks
        description: KeepMyChunks command
        aliases: [kmc]
